### ISSUE TITLE
converting Error to anyhow::Error

### ISSUE THREAD

**Issue by burrbull** [abakay/irx-config#10]
When I trying to use `?` on `irx_config` Result I see:
![изображение](https://user-images.githubusercontent.com/3072754/188559607-043ef9ee-8a27-42c3-8561-5627d7d94392.png)

Related issue:
https://github.com/dtolnay/anyhow/issues/66

Although, it is not blocking for me to use this crate.

**Comment by abakay** [comment]
Could you please provide some code samples/snippets for that issue?

**Comment by burrbull** [comment]
You could look at https://github.com/rust-embedded/svd2rust/pull/656
Just remove any of `map_err` in `parse_configs`

**Comment by Emilgardis** [comment]
following is needed to fix the issue

```diff
diff --git a/src/lib.rs b/src/lib.rs
index c105ec0..30561fe 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -20,7 +20,7 @@ use std::result::Result as StdResult;
 pub type Result<T> = StdResult<T, Error>;
 
 /// A result type with any error.
-pub type AnyResult<T> = StdResult<T, Box<dyn StdError>>;
+pub type AnyResult<T> = StdResult<T, Box<dyn StdError + Send + Sync + 'static>>;
 
 type CowString<'a> = Cow<'a, str>;
 type AnyParser = Box<dyn Parse>;
@@ -39,7 +39,7 @@ pub enum Error {
     #[error("Failed to serialize/deserialize")]
     SerdeError(#[from] SerdeError),
     #[error("Failed to parse value")]
-    ParseValue(#[from] Box<dyn StdError>),
+    ParseValue(#[from] Box<dyn StdError + Send + Sync + 'static>),
     #[error(transparent)]
     IO(#[from] std::io::Error),
 }

```

**Comment by abakay** [comment]
@Emilgardis, thanks for the patch, I will try it shortly.

**Comment by abakay** [comment]
Hi @Emilgardis,

Is it really necessary to add `'static` bound? I tried `Box<dyn StdError + Send + Sync>` and it is works. Plus all `Box<dyn ...>` declarations in `std::io::Error` has `Send` and `Sync` bounds no `'static`.

Please advise.

**Comment by Emilgardis** [comment]
@abakay the `+ 'static` is needed for methods on `dyn Error + 'static`, which include downcast and more, see https://doc.rust-lang.org/std/error/trait.Error.html#implementations. 

The compiler will insert an implicit `'static` on trait objects, so being explicit about it is technically not needed, but imo it's nice to include.
