### ISSUE TITLE
How to work with clap boolean flags?

### ISSUE THREAD

**Issue by burrbull** [abakay/irx-config#7]
I'm trying to parse flags as boolean config fields. But when I enable cli flag:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid type: integer `1`, expected a boolean", line: 0, column: 0))'
```

**Comment by abakay** [comment]
Hi @burrbull,

Current conversion logic of command-line parameters without values (`takes_value(false)`) is a value become the number of occurrences of such parameter. The reasons behind that is:

1. The use case with multiple occurrences have to be covered. For example the level of verbosity could be set as following: `-vvv`.
2. The value type of such parameters is more "stable" this way, it is always integer.

Possible logic changes could be: if parameter does not take any value and it is not allowed to have multiple occurrences by `clap` API then it will have boolean `true` value. Probably it could be configurable behaviour.

I will come up with some fix(es) shortly, but in meantime you could change type of your parameter in structure to integer.

Thank you for your feedback.
