### ISSUE TITLE
How to ignore parser if parser associated file is absent?

### ISSUE THREAD

**Issue by burrbull** [abakay/irx-config#8]

**Comment by abakay** [comment]
Hi @burrbull,

The file availability/existence is usually checked by business logic, but I see how it could be useful/ergonomic in that context.

I will provide some fix(es) shorty, but in meantime as a workaround your could write a custom parser (they supported, see examples in documentation [Custom parser](https://github.com/abakay/irx-config#custom-parser) which will be very thin wrapper on top of any embedded file based parsers.

Thanks for your feedback.
